(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'dictonary'"
p3
sS'layer'
p4
S'/home/luis/Dropbox/Innovare/web2py/applications/econary/controllers/admin.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f36fad5f7b0, file "/home/luis/Dropbox/Innovare/web2py/applications/econary/controllers/admin.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/luis/Dropbox/Innovare/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/luis/Dropbox/Innovare/web2py/applications/econary/controllers/admin.py", line 12, in <module>\n  File "/home/luis/Dropbox/Innovare/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/luis/Dropbox/Innovare/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/luis/Dropbox/Innovare/web2py/applications/econary/controllers/admin.py", line 3, in index\n    words = db(db.dictonary).select()\n  File "/home/luis/Dropbox/Innovare/web2py/gluon/packages/dal/pydal/base.py", line 670, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'dictonary\'\n'
p11
s.